default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: co_order_rails_development
  username: root
  password: P@ssword1234
  host: localhost

development:
  <<: *default
  database: co_order_rails_development

test:
  <<: *default
  database: co_order_rails_test


production:
  <<: *default
  database: co_order_rails_production
  username: co_order_rails
  password: <%= ENV['CO_ORDER_RAILS_DATABASE_PASSWORD'] %>
